<?php

declare(strict_types=1);

return [
    'defaults' => [
        'enabled' => true,
        'needs_proxy' => false,
        'max_attempts' => 3,
        'fallback_gap_seconds' => [
            'default' => 30,
            'min' => 30,
            'max' => 120,
        ],
        'circuit' => [
            'failure_threshold' => 3,
            'cooldown_seconds' => 300,
        ],
        'queue' => [
            'stale_claim_timeout_seconds' => 900,
        ],
        'normalize' => [
            // Per-source mapping of crawlerx metadata{} keys onto MovieDraft
            // fields. The first non-empty match in each alias list wins. A
            // source may override any key via
            // `sources.<slug>.normalize.key_map` (merged over these defaults).
            'title_locale' => 'jp',
            'key_map' => [
                'maker' => ['maker', 'Maker', 'メーカー', 'maker_label', 'publisher'],
                'label' => ['label', 'Label', 'レーベル'],
                'series' => ['series', 'Series'],
                'score' => ['rating', 'Rating', 'score', '評価'],
                'genres' => ['genres', 'Genre', 'ジャンル', 'categories'],
                'magnets' => ['downloads', 'download_url'],
                'hls' => ['stream', 'sample_streams', 'sample_video_url'],
                'description' => ['description', 'Description', 'あらすじ', '紹介', 'summary'],
                'directors' => ['director', 'Director', 'directors', '監督'],
            ],
        ],
        // Default fetch profile for crawlerx (HTTP → impersonate → PW/stealth → Flare).
        // Override per source with sources.<slug>.fetch.profile.
        'fetch' => [
            'profile' => env('JVMETA_FETCH_PROFILE', 'browser_likely'),
            'http' => [
                'timeout' => (int) env('JVMETA_FETCH_TIMEOUT', 90),
            ],
        ],
    ],
    'sources' => [
        'javdb' => [
            'name' => 'JavDB',
            'base_url' => 'https://javdb.com',
            'priority' => 10,
            'gap_seconds_default' => 20,
            'gap_seconds_min' => 20,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://javdb.com/'],
        ],
        'javdatabase' => [
            'name' => 'JAV Database',
            'base_url' => 'https://www.javdatabase.com',
            'priority' => 20,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 45,
            'performer_listing_urls' => ['https://www.javdatabase.com/idols/'],
        ],
        'javlibrary' => [
            'name' => 'JAVLibrary',
            'base_url' => 'https://www.javlibrary.com',
            'priority' => 30,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 45,
            'movie_listing_urls' => ['https://www.javlibrary.com/en/vl_newrelease.php'],
            'performer_listing_urls' => ['https://www.javlibrary.com/en/star_list.php'],
        ],
        'javbus' => [
            'name' => 'JavBus',
            'base_url' => 'https://www.javbus.com',
            'priority' => 35,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 45,
            'movie_listing_urls' => ['https://www.javbus.com/'],
            'performer_listing_urls' => ['https://www.javbus.com/en/actresses'],
        ],
        'missav' => [
            'name' => 'MissAV',
            'base_url' => 'https://missav.ws/en',
            'priority' => 40,
            'gap_seconds_default' => 5,
            'gap_seconds_min' => 2,
            'gap_seconds_max' => 30,
            'movie_listing_urls' => ['https://missav.ws/en/new'],
        ],
        'fc2' => [
            'name' => 'FC2 Content Market',
            'base_url' => 'https://adult.contents.fc2.com',
            'priority' => 50,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://adult.contents.fc2.com/'],
        ],
        'onejav' => [
            'name' => 'OneJav',
            'base_url' => 'https://onejav.com',
            'priority' => 60,
            'gap_seconds_default' => 2,
            'gap_seconds_min' => 0.5,
            'gap_seconds_max' => 15,
            'movie_listing_urls' => ['https://onejav.com/new', 'https://onejav.com/popular/', 'https://onejav.com/tag/'],
        ],
        'javbtc' => [
            'name' => 'JavBTC',
            'base_url' => 'https://javbtc.com',
            'priority' => 70,
            'gap_seconds_default' => 3,
            'gap_seconds_min' => 1,
            'gap_seconds_max' => 20,
            'movie_listing_urls' => ['https://javbtc.com/'],
        ],
        '141jav' => [
            'name' => '141Jav',
            'base_url' => 'https://www.141jav.com',
            'priority' => 80,
            'gap_seconds_default' => 2,
            'gap_seconds_min' => 0.5,
            'gap_seconds_max' => 15,
            'movie_listing_urls' => ['https://www.141jav.com/new', 'https://www.141jav.com/popular/', 'https://www.141jav.com/tag/'],
        ],
        'ffjav' => [
            'name' => 'FFJav',
            'base_url' => 'https://ffjav.com',
            'priority' => 90,
            'gap_seconds_default' => 4,
            'gap_seconds_min' => 1,
            'gap_seconds_max' => 20,
            'movie_listing_urls' => ['https://ffjav.com/javtorrent/', 'https://ffjav.com/popular/'],
        ],
        'avfan' => [
            'name' => 'Avfan',
            'base_url' => 'https://avfan.com',
            'priority' => 100,
            'gap_seconds_default' => 5,
            'gap_seconds_min' => 2,
            'gap_seconds_max' => 30,
            'movie_listing_urls' => ['https://avfan.com/en'],
        ],
        'jable' => [
            'name' => 'Jable',
            'base_url' => 'https://en.jable.tv',
            'priority' => 110,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 3,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://en.jable.tv/new-release/'],
            'performer_listing_urls' => ['https://en.jable.tv/models/'],
            'normalize' => ['title_locale' => 'en'],
        ],
        'xcity' => [
            'name' => 'XCITY',
            'base_url' => 'https://xxx.xcity.jp',
            'priority' => 120,
            'gap_seconds_default' => 5,
            'gap_seconds_min' => 2,
            'gap_seconds_max' => 30,
            'movie_listing_urls' => ['https://xxx.xcity.jp/avod/list/?style=simple'],
            'performer_listing_urls' => ['https://xxx.xcity.jp/idol/'],
        ],
        'warashi' => [
            'name' => 'Warashi',
            'base_url' => 'https://warashi-asian-pornstars.fr',
            'priority' => 130,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 45,
            'performer_listing_urls' => ['https://warashi-asian-pornstars.fr/en/s-2-2/female-pornstars/toutes/all/page/1'],
            'gallery_urls' => ['https://warashi-asian-pornstars.fr/en/s-7-0/yuna-ishikawa/female-asian-pornstar/photo-gallery/56092'],
        ],
        'minnanoav' => [
            'name' => 'Minnano AV',
            'base_url' => 'https://www.minnano-av.com',
            'priority' => 140,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 3,
            'gap_seconds_max' => 45,
            'performer_listing_urls' => ['https://www.minnano-av.com/actress_list.php'],
        ],
        'onepondo' => [
            'name' => '1Pondo',
            'base_url' => 'https://en.1pondo.tv',
            'priority' => 150,
            'gap_seconds_default' => 6,
            'gap_seconds_min' => 2,
            'gap_seconds_max' => 30,
            'movie_listing_urls' => ['https://en.1pondo.tv/list/?o=n'],
            'normalize' => ['title_locale' => 'en'],
        ],
        'caribbeancom' => [
            'name' => 'Caribbeancom',
            'base_url' => 'https://en.caribbeancom.com',
            'priority' => 160,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://en.caribbeancom.com/eng/index2.htm'],
        ],
        'heyzo' => [
            'name' => 'HEYZO',
            'base_url' => 'https://en.heyzo.com',
            'priority' => 170,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://en.heyzo.com/listpages/all_1.html'],
        ],
        'tokyohot' => [
            'name' => 'Tokyo-Hot',
            'base_url' => 'https://my.tokyo-hot.com',
            'priority' => 180,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://my.tokyo-hot.com/index?lang=en'],
        ],
        'duga' => [
            'name' => 'DUGA',
            'base_url' => 'https://duga.jp',
            'priority' => 190,
            'gap_seconds_default' => 10,
            'gap_seconds_min' => 5,
            'gap_seconds_max' => 60,
            'movie_listing_urls' => ['https://duga.jp/main/'],
        ],
        'eporner' => [
            'name' => 'EPORNER',
            'base_url' => 'https://www.eporner.com',
            'priority' => 200,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 4,
            'gap_seconds_max' => 60,
            'gallery_urls' => ['https://www.eporner.com/gallery/xKeoFe7VHmO/Iori-Kogawa-gu-chuaniori-STAR-836-Uncensored-Leak/'],
        ],
        'aisex' => [
            'name' => 'Aisex',
            'base_url' => 'https://www.aisex.jp',
            'priority' => 210,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 4,
            'gap_seconds_max' => 60,
            'performer_listing_urls' => ['https://www.aisex.jp/actress/'],
        ],
        'avfan_profiles' => [
            'name' => 'Avfan Profiles',
            'base_url' => 'https://av-fan.tokyo',
            'priority' => 220,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 4,
            'gap_seconds_max' => 60,
            'performer_listing_urls' => ['https://av-fan.tokyo/actress/cup/A.html'],
        ],
        'avjoho' => [
            'name' => 'Avjoho',
            'base_url' => 'https://db.avjoho.com',
            'priority' => 230,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 4,
            'gap_seconds_max' => 60,
            'performer_listing_urls' => ['https://db.avjoho.com/category/%e3%83%87%e3%83%93%e3%83%a5%e3%83%bc%ef%bc%882025%e5%b9%b4-%ef%bc%89/'],
        ],
        'javphotos' => [
            'name' => 'JavPhotos',
            'base_url' => 'https://jav.photos',
            'priority' => 240,
            'gap_seconds_default' => 8,
            'gap_seconds_min' => 4,
            'gap_seconds_max' => 60,
            'gallery_listing_urls' => ['https://jav.photos/free/'],
        ],
    ],
];
